# Header
menu:
  首页: /life
  技术: /
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets_index:
- recent_posts
- category
- tagcloud
- archive

widgets_post:
- toc

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: